server:
  port: 8083

spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: "dossier"
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: ru.kalinin.dossier.dto.EmailMessage
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: ru.kalinin.**

  profiles:
    active: ${ACTIVE_PROFILE:dev}

  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_ID}
    password: ${EMAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
            connectiontimeout: 10000
            timeout: 10000
            writetimeout: 10000


logging:
  level:
    org:
      zalando:
        logbook: TRACE
      springframework:
        web:
          servlet:
            DispatcherServlet: debug
    web: info
    ru.neoflex.statement.feign: debug

deal:
  url: 'http://deal:8081/deal'