# yaml
name: CI Pipeline

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    strategy:
      fail-fast: false
      matrix:
        module: ['common', 'calculator', 'deal', 'statement', 'dossier']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'maven'

      - name: Build module with Maven (skip tests)
        run: mvn -B -pl ${{ matrix.module }} -am clean install -DskipTests

      - name: Run tests and generate coverage report
        if: ${{ matrix.module != 'dossier' && matrix.module != 'common' }}
        run: mvn -B -pl ${{ matrix.module }} -am test jacoco:report

      - name: Upload coverage to Codecov
        if: ${{ matrix.module != 'dossier' && matrix.module != 'common' }}
        uses: codecov/codecov-action@v3
        with:
          files: ${{ matrix.module }}/target/site/jacoco/jacoco.xml
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

  sonar:
    name: SonarCloud
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Sanitize Sonar vars
        run: |
          echo "SONAR_ORG=$(echo "${{ vars.SONAR_ORG }}" | tr -d '[:space:]')" >> "$GITHUB_ENV"
          echo "SONAR_PROJECT_KEY=$(echo "${{ vars.SONAR_PROJECT_KEY }}" | tr -d '[:space:]')" >> "$GITHUB_ENV"

      # Запускаем анализ один раз из корня; тесты выполняются для генерации JaCoCo XML
      - name: SonarCloud scan (root, once)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: >
          mvn -B verify
          org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=${SONAR_ORG}
          -Dsonar.projectKey=${SONAR_PROJECT_KEY}